// Copyright Cozystack Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestPrependLeadingComments_PreservesAllLines pins the canonical
// in-place rewrite shape (#178): operator-authored `#`-prefixed
// and blank lines that lived above the modeline in the source file
// are re-emitted at the top of the regenerated content. Without
// this guarantee, `talm template -I` silently strips operator
// documentation on every rewrite.
func TestPrependLeadingComments_PreservesAllLines(t *testing.T) {
	leading := []string{
		"# Note 1: reset 2026-05-12 after ticket OPS-1234",
		"# Note 2: DO NOT edit values directly",
		"",
		"# Note 3: extra context",
	}
	rendered := "# talm: nodes=[\"1.2.3.4\"]\n# THIS FILE IS AUTOGENERATED…\nmachine:\n  type: controlplane\n"

	got := prependLeadingComments(leading, rendered)

	// Every leading line must appear, in order, before the
	// rendered output.
	want := "# Note 1: reset 2026-05-12 after ticket OPS-1234\n" +
		"# Note 2: DO NOT edit values directly\n" +
		"\n" +
		"# Note 3: extra context\n" +
		rendered
	if got != want {
		t.Errorf("prependLeadingComments mismatch\ngot:\n%s\n\nwant:\n%s", got, want)
	}
}

// TestPrependLeadingComments_EmptyLeading_ReturnsOutputUnchanged
// pins the degenerate case: no leading comments → output passes
// through verbatim. Pinning this avoids a future refactor where
// the helper accidentally appends an empty line for the
// "no comments" case.
func TestPrependLeadingComments_EmptyLeading_ReturnsOutputUnchanged(t *testing.T) {
	rendered := "# talm: nodes=[\"1.2.3.4\"]\nmachine:\n  type: controlplane\n"

	if got := prependLeadingComments(nil, rendered); got != rendered {
		t.Errorf("nil leading must pass output through; got %q want %q", got, rendered)
	}

	if got := prependLeadingComments([]string{}, rendered); got != rendered {
		t.Errorf("empty leading must pass output through; got %q want %q", got, rendered)
	}
}

// TestWriteInplaceRendered_PreservesOperatorCommentsAboveModeline
// pins the end-to-end behaviour wired through templateOneFile:
// when `talm template -I` rewrites a node file, the operator's
// leading-comment block survives the regeneration. Reaches in via
// the same writeInplaceRendered helper templateOneFile uses, so a
// future refactor that changes the call site (different writer,
// different file path, etc.) but keeps the helper signature must
// still pass this contract.
func TestWriteInplaceRendered_PreservesOperatorCommentsAboveModeline(t *testing.T) {
	dir := t.TempDir()
	file := filepath.Join(dir, "node.yaml")

	leading := []string{
		"# This node was reset 2026-05-12 after ticket OPS-1234",
		"# DO NOT edit values directly; modify values.yaml and re-template",
	}
	rendered := "# talm: nodes=[\"1.2.3.4\"], endpoints=[\"1.2.3.4\"], templates=[\"templates/cp.yaml\"]\n" +
		"# THIS FILE IS AUTOGENERATED. PREFER TEMPLATE EDITS OVER MANUAL ONES.\n" +
		"machine:\n  type: controlplane\n"

	combined := prependLeadingComments(leading, rendered)

	if err := writeInplaceRendered(file, combined); err != nil {
		t.Fatalf("writeInplaceRendered: %v", err)
	}

	got, err := os.ReadFile(file)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}

	// The written file must start with the operator's leading
	// lines, then the modeline, then the rendered body — in this
	// exact order.
	gotStr := string(got)
	if !strings.HasPrefix(gotStr, leading[0]+"\n"+leading[1]+"\n") {
		t.Errorf("operator comments missing or out of order at start of file; got:\n%s", gotStr)
	}

	modelineIdx := strings.Index(gotStr, "# talm:")
	if modelineIdx <= 0 {
		t.Errorf("modeline must follow the leading comments, not start the file; got:\n%s", gotStr)
	}
}
