// Copyright Cozystack Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Contract: after a successful `talm upgrade`, the upgrade handler
// must point-patch machine.install.image in every -f node body so the
// next `talm apply` does not silently revert install.image. These
// tests pin the patcher's shape on disk: scalar value swap,
// idempotency, silent-skip on files without the key, error surface
// when the YAML shape conflicts with the contract, and preservation
// of the autogen banner / talm modeline / per-key comments that
// `talm template -I` writes upstream of upgrade.

package commands

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

const (
	testOldImage = "ghcr.io/cozystack/cozystack/talos:v1.12.6"
	testNewImage = "ghcr.io/cozystack/cozystack/talos:v1.13.0"
)

func writeTempFile(t *testing.T, content string) string {
	t.Helper()

	dir := t.TempDir()
	path := filepath.Join(dir, "node0.yaml")

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("seeding tempfile: %v", err)
	}

	return path
}

// Contract: a node body with machine.install.image has the scalar
// swapped in-place. The rest of the YAML body — including the talm
// modeline (`# talm: ...`), the autogen banner, sibling keys under
// machine.install, and any per-key comments — must survive the
// round-trip. yaml.v3's node-based parse keeps comments attached;
// regression would surface here as either an unchanged image (write
// silently failed) or a destroyed banner / modeline.
func TestContract_WriteBackInstallImage_HappyPath(t *testing.T) {
	body := `# talm: nodes=["192.0.2.10"], endpoints=["192.0.2.10"], templates=["templates/controlplane.yaml"]
# THIS FILE IS AUTOGENERATED. PREFER TEMPLATE EDITS OVER MANUAL ONES.
machine:
  type: controlplane
  install:
    disk: /dev/sda
    image: ` + testOldImage + `
cluster:
  clusterName: test
`

	path := writeTempFile(t, body)
	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if !patched {
		t.Fatalf("expected patched=true on happy path, got false")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("re-reading: %v", err)
	}
	gotStr := string(got)

	// New image present.
	if !strings.Contains(gotStr, testNewImage) {
		t.Errorf("expected new image %q in output, got:\n%s", testNewImage, gotStr)
	}

	// Old image gone.
	if strings.Contains(gotStr, testOldImage) {
		t.Errorf("old image %q still present after writeback:\n%s", testOldImage, gotStr)
	}

	// Modeline preserved (the first-line comment yaml.v3 keeps as the
	// document's HeadComment).
	if !strings.Contains(gotStr, `# talm: nodes=["192.0.2.10"]`) {
		t.Errorf("modeline missing after writeback:\n%s", gotStr)
	}

	// Sibling key preserved.
	if !strings.Contains(gotStr, "disk: /dev/sda") {
		t.Errorf("sibling key machine.install.disk missing after writeback:\n%s", gotStr)
	}
}

// Contract: when the body's machine.install.image already equals the
// target, writeback is a no-op — it does NOT rewrite the file on
// disk. Pinned via mtime: an operator who runs `talm template -I` to
// sync, then `talm upgrade`, then `talm upgrade` again must not see
// the file's mtime bump on the redundant pass (touching the file
// would re-trigger git status, file watchers, etc.).
func TestContract_WriteBackInstallImage_NoOpWhenAlreadyTarget(t *testing.T) {
	body := `machine:
  install:
    image: ` + testNewImage + `
`
	path := writeTempFile(t, body)

	statBefore, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat before: %v", err)
	}

	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if patched {
		t.Errorf("expected patched=false when body already on target image, got true")
	}

	statAfter, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after: %v", err)
	}

	if !statBefore.ModTime().Equal(statAfter.ModTime()) {
		t.Errorf("expected no-op (mtime stable), got mtime change %v -> %v", statBefore.ModTime(), statAfter.ModTime())
	}
}

// Contract: a file with no machine.install.image key is silently
// skipped. The upgrade handler calls writeBackInstallImageToFiles
// over every -f file; side-patches, orphan patches, and any other
// shape without machine.install.image legitimately surface here, and
// erroring would block the upgrade success path on irrelevant inputs.
func TestContract_WriteBackInstallImage_SkipsFileWithoutKey(t *testing.T) {
	cases := []struct {
		name string
		body string
	}{
		{
			"side-patch with only network",
			"machine:\n  network:\n    hostname: foo\n",
		},
		{
			"no machine key at all",
			"cluster:\n  clusterName: foo\n",
		},
		{
			"machine.install without image",
			"machine:\n  install:\n    disk: /dev/sda\n",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := writeTempFile(t, tc.body)
			patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
			if err != nil {
				t.Fatalf("expected silent skip, got error: %v", err)
			}
			if patched {
				t.Errorf("expected patched=false on skip path, got true")
			}

			got, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("re-reading: %v", err)
			}
			if string(got) != tc.body {
				t.Errorf("expected file unchanged on skip path, got:\n%s\nwant:\n%s", string(got), tc.body)
			}
		})
	}
}

// Contract: a structurally wrong shape at the machine.install.image
// path surfaces as an error, not a silent skip. An operator who
// edited the body into an invalid form must see the failure rather
// than have it masked by the silent-skip branch (which is reserved
// for the "key absent" shape).
func TestContract_WriteBackInstallImage_StructuralErrors(t *testing.T) {
	cases := []struct {
		name string
		body string
	}{
		{
			"machine.install.image is a mapping",
			"machine:\n  install:\n    image:\n      ref: foo\n",
		},
		{
			"machine.install is a scalar",
			"machine:\n  install: not-a-mapping\n",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := writeTempFile(t, tc.body)
			if _, err := writeBackInstallImageToNodeBody(path, testNewImage); err == nil {
				t.Errorf("expected structural error for %q, got nil", tc.body)
			}
		})
	}
}

// Contract: the writeback re-emits the body with the same indent
// shape it was seeded with. talm-rendered node bodies use 2-space
// indent throughout (see the `nindent 2/4/6` ladder in the chart
// helpers); yaml.v3's default Marshal emits 4-space indent which
// would re-indent every line under machine.* on round-trip and
// flood `git diff` with cosmetic noise — making the operator-visible
// claim "git diff shows a single-line image change" (manual-test-plan
// E4) false.
//
// Strategy: seed a body, capture it line-by-line, run the writeback,
// then assert every line is byte-identical EXCEPT the single
// `    image: <ref>` line whose right-hand side changed. A regression
// that re-indented the whole file would fail every nested line.
func TestContract_WriteBackInstallImage_PreservesIndentShape(t *testing.T) {
	body := `# talm: nodes=["192.0.2.10"], endpoints=["192.0.2.10"], templates=["templates/controlplane.yaml"]
# THIS FILE IS AUTOGENERATED. PREFER TEMPLATE EDITS OVER MANUAL ONES.
machine:
  type: controlplane
  kubelet:
    nodeIP:
      validSubnets:
        - 192.0.2.0/24
  install:
    disk: /dev/sda
    image: ` + testOldImage + `
cluster:
  clusterName: test
`
	path := writeTempFile(t, body)
	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if !patched {
		t.Fatalf("expected patched=true, got false")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("re-reading: %v", err)
	}

	beforeLines := strings.Split(body, "\n")
	afterLines := strings.Split(string(got), "\n")

	if len(beforeLines) != len(afterLines) {
		t.Fatalf("expected line count to match (writeback must not add/remove lines), got before=%d after=%d\nafter:\n%s", len(beforeLines), len(afterLines), string(got))
	}

	for i := range beforeLines {
		before := beforeLines[i]
		after := afterLines[i]

		if strings.HasPrefix(strings.TrimSpace(before), "image:") {
			// The image scalar line is allowed to differ — but its
			// indent prefix must be unchanged.
			beforeIndent := before[:len(before)-len(strings.TrimLeft(before, " "))]
			afterIndent := after[:len(after)-len(strings.TrimLeft(after, " "))]
			if beforeIndent != afterIndent {
				t.Errorf("image line indent changed: %q -> %q", beforeIndent, afterIndent)
			}
			if !strings.Contains(after, testNewImage) {
				t.Errorf("image line should now contain %q, got %q", testNewImage, after)
			}

			continue
		}

		if before != after {
			t.Errorf("line %d unexpectedly changed:\n  before: %q\n  after:  %q", i+1, before, after)
		}
	}
}

// Contract: the writeback preserves the source file's permission
// bits. An operator who hardened node-body permissions (chmod 0600
// for some reason) must not get them silently relaxed to the
// presetFileMode 0o644 by the writeback. Only when Stat fails does
// the writeback fall back to presetFileMode.
//
// Windows is skipped: NTFS does not honour Unix permission bits, so
// os.FileInfo.Mode().Perm() always returns 0o666 there (see the
// project memory entry on cross-platform Go testing).
func TestContract_WriteBackInstallImage_PreservesFileMode(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Unix permission bits not meaningful on NTFS")
	}

	body := "machine:\n  install:\n    image: " + testOldImage + "\n"
	path := writeTempFile(t, body)

	if err := os.Chmod(path, 0o600); err != nil {
		t.Fatalf("chmod seed: %v", err)
	}

	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if !patched {
		t.Fatalf("expected patched=true, got false")
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after: %v", err)
	}
	if got, want := info.Mode().Perm(), os.FileMode(0o600); got != want {
		t.Errorf("file mode after writeback: got %v, want %v (operator-hardened mode must be preserved)", got, want)
	}
}

// Contract: a multi-document node body (cozystack v1.12+ render
// shape: machine + cluster + RegistryMirrorConfig + LinkConfig +
// Layer2VIPConfig + VLANConfig separated by `---`) preserves every
// non-machine document on round-trip. yaml.Unmarshal reads only the
// first document — using it on a multi-doc body would silently erase
// the registry / link / VIP / VLAN config from the file on disk.
// The writeback uses yaml.NewDecoder in a loop and re-emits every
// document through a single yaml.NewEncoder; this test pins that
// shape against the exact failure mode.
func TestContract_WriteBackInstallImage_PreservesAllDocuments(t *testing.T) {
	body := `# talm: nodes=["192.0.2.10"], endpoints=["192.0.2.10"], templates=["templates/controlplane.yaml"]
machine:
  type: controlplane
  install:
    disk: /dev/sda
    image: ` + testOldImage + `
cluster:
  clusterName: test
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://mirror.gcr.io
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
up: true
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: eth0
vip: 192.0.2.1
`
	path := writeTempFile(t, body)
	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if !patched {
		t.Fatalf("expected patched=true on multi-doc body, got false")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("re-reading: %v", err)
	}
	gotStr := string(got)

	// Image swap landed.
	if !strings.Contains(gotStr, testNewImage) {
		t.Errorf("new image %q missing from output:\n%s", testNewImage, gotStr)
	}
	if strings.Contains(gotStr, testOldImage) {
		t.Errorf("old image %q still present after writeback:\n%s", testOldImage, gotStr)
	}

	// Every non-machine document survived. Assert by content
	// fingerprints — the kind names are unique enough to pin the
	// presence of each document.
	for _, kind := range []string{"RegistryMirrorConfig", "LinkConfig", "Layer2VIPConfig"} {
		if !strings.Contains(gotStr, "kind: "+kind) {
			t.Errorf("document with kind %s missing after writeback (multi-doc truncated?):\n%s", kind, gotStr)
		}
	}

	// Pin the document count via the `---` separator. The input has
	// 4 documents (3 separators); the output must have the same.
	wantSeparators := strings.Count(body, "\n---\n")
	gotSeparators := strings.Count(gotStr, "\n---\n")
	if wantSeparators != gotSeparators {
		t.Errorf("document-separator count changed: want %d, got %d\noutput:\n%s", wantSeparators, gotSeparators, gotStr)
	}

	// Content of preserved documents is byte-for-byte the same. Walk
	// the registry-doc body and confirm each line appears verbatim.
	for _, marker := range []string{
		"name: docker.io",
		"url: https://mirror.gcr.io",
		"vip: 192.0.2.1",
	} {
		if !strings.Contains(gotStr, marker) {
			t.Errorf("expected marker %q from a preserved document, got:\n%s", marker, gotStr)
		}
	}
}

// Contract: writeback locates machine.install.image even when it is
// NOT in the first document. The cozystack preset emits machine
// first, but a hand-authored body that puts it elsewhere (e.g.
// network docs first, then machine) must still patch correctly.
// Defensive coverage against a future chart re-ordering.
func TestContract_WriteBackInstallImage_FindsImageInAnyDocument(t *testing.T) {
	body := `apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://mirror.gcr.io
---
machine:
  install:
    image: ` + testOldImage + `
`
	path := writeTempFile(t, body)
	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if !patched {
		t.Fatalf("expected patched=true when machine doc is second, got false")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("re-reading: %v", err)
	}
	if !strings.Contains(string(got), testNewImage) {
		t.Errorf("new image missing; image not patched when not in first doc:\n%s", string(got))
	}
	if !strings.Contains(string(got), "kind: RegistryMirrorConfig") {
		t.Errorf("first doc lost on writeback:\n%s", string(got))
	}
}

// Contract: a multi-document body that is already on the target
// image is a no-op — mtime stays stable so the redundant pass
// doesn't trigger git-status churn or file watchers, AND every
// non-machine document is preserved unchanged (the no-op path must
// not silently truncate the body even though no rewrite is needed).
func TestContract_WriteBackInstallImage_NoOpOnMultiDocAlreadyTarget(t *testing.T) {
	body := `machine:
  install:
    image: ` + testNewImage + `
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
`
	path := writeTempFile(t, body)
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read before: %v", err)
	}
	statBefore, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat before: %v", err)
	}

	patched, err := writeBackInstallImageToNodeBody(path, testNewImage)
	if err != nil {
		t.Fatalf("writeBackInstallImageToNodeBody: %v", err)
	}
	if patched {
		t.Errorf("expected patched=false (already on target), got true")
	}

	statAfter, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after: %v", err)
	}
	if !statBefore.ModTime().Equal(statAfter.ModTime()) {
		t.Errorf("expected mtime stable on no-op multi-doc path, got %v -> %v", statBefore.ModTime(), statAfter.ModTime())
	}

	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read after: %v", err)
	}
	if string(before) != string(after) {
		t.Errorf("expected file unchanged on no-op multi-doc path; before:\n%s\nafter:\n%s", before, after)
	}
}

// Contract: writeBackInstallImageToFiles iterates the file list,
// processing each via writeBackInstallImageToNodeBody. An empty image
// argument short-circuits to no-op (the upgrade handler reaches this
// with targetImage="" when --image was unset AND the values.yaml
// resolution was bypassed — there is nothing to write back). A list
// with files of mixed shapes (one with image, one without) processes
// both — the no-key file is silently skipped, the keyed file is
// patched.
func TestContract_WriteBackInstallImage_FilesFanOut(t *testing.T) {
	keyed := writeTempFile(t, "machine:\n  install:\n    image: "+testOldImage+"\n")
	noKey := writeTempFile(t, "machine:\n  network:\n    hostname: foo\n")

	if err := writeBackInstallImageToFiles([]string{keyed, noKey}, testNewImage); err != nil {
		t.Fatalf("writeBackInstallImageToFiles: %v", err)
	}

	keyedOut, err := os.ReadFile(keyed)
	if err != nil {
		t.Fatalf("re-read keyed: %v", err)
	}
	if !strings.Contains(string(keyedOut), testNewImage) {
		t.Errorf("keyed file not patched: %s", string(keyedOut))
	}

	// Empty image: no-op even on a keyed file.
	keyedRetry := writeTempFile(t, "machine:\n  install:\n    image: "+testOldImage+"\n")
	if err := writeBackInstallImageToFiles([]string{keyedRetry}, ""); err != nil {
		t.Fatalf("writeBackInstallImageToFiles with empty image: %v", err)
	}
	retryOut, err := os.ReadFile(keyedRetry)
	if err != nil {
		t.Fatalf("re-read retry: %v", err)
	}
	if !strings.Contains(string(retryOut), testOldImage) {
		t.Errorf("empty image arg should be a no-op; file changed: %s", string(retryOut))
	}
}
