// Copyright Cozystack Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"fmt"
	"strings"

	"github.com/Masterminds/semver/v3"
)

// devVersionStamp is the placeholder version written into a project's
// Chart.yaml when it is generated by a non-release (dev) talm build. It
// mirrors the sentinel used in main.go's initConfig. A project carrying
// this value was never stamped by a real release, so there is nothing
// meaningful to compare against.
const devVersionStamp = "0.1.0"

// CheckChartVersion compares the talm binary version against the version
// stamped into the project's Chart.yaml at `talm init` / `talm init --update`
// time.
//
// talm vendors its preset and library charts into the project directory at
// init time; rendering (template/apply/upgrade) then reads that local copy,
// never the binary's embedded charts. So upgrading the talm binary does not
// touch the vendored charts/talm/ — they stay frozen at the version that last
// ran init. This function surfaces that drift.
//
// binaryVersion is main.Version (e.g. "v0.30.0", or "dev" for source builds).
// chartVersion is the project Chart.yaml `version:` field (e.g. "0.27.0").
//
// It returns (true, message) only when both versions are real, parseable
// releases that differ. It returns (false, "") — i.e. stays silent — when
// either side is a dev build, the sentinel, empty, or unparseable, so it
// never raises a false alarm against source builds or unstamped projects.
func CheckChartVersion(binaryVersion, chartVersion string) (bool, string) {
	bin, err := semver.NewVersion(strings.TrimPrefix(binaryVersion, "v"))
	if err != nil {
		// dev / unparseable binary — nothing meaningful to compare.
		return false, ""
	}

	normalizedChart := strings.TrimPrefix(chartVersion, "v")
	if normalizedChart == "" || normalizedChart == devVersionStamp {
		// project was never stamped by a release build.
		return false, ""
	}

	chart, err := semver.NewVersion(normalizedChart)
	if err != nil {
		return false, ""
	}

	if bin.Equal(chart) {
		return false, ""
	}

	return true, fmt.Sprintf(
		"talm binary is %s but this project's charts were vendored by talm %s; "+
			"run `talm init --update` to sync charts/talm/ (or ignore if this is intentional)",
		bin.String(), chart.String(),
	)
}
